version: "3"
services:
  frontend:
    container_name: frontend
    build: Frontend/.
    expose:
      - 3000
    command: npm start
    env_file:
      - ./Frontend/frontend.env
    volumes:
      - ./Frontend:/usr/frontend
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - frontend
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Nginx/logs/:/var/log/nginx/
      - ./Nginx/http.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    restart: always
